name: Laravel CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4" # Sesuaikan dengan versi PHP yang Anda gunakan

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: php artisan test
